### ISSUE TITLE
Menu sections in new website are hard to find

### ISSUE THREAD

**Issue by juliohm** [lazarusA/BeautifulMakie#11]
When I open the website on my desktop, the menu sections are all the way to the right with grayish color on white background. Perhaps you could move these to the left of the top bar and change the color to something more visible.

**Comment by juliohm** [comment]
![image](https://user-images.githubusercontent.com/3345261/126901066-457f13ac-1575-4bcc-8d6e-e3277027387e.png)

**Comment by lazarusA** [comment]
does it look better now? If it does please close the issue.

**Comment by juliohm** [comment]
Certainly looks more visible! It could be more centered but I think it is a matter of taste. Also, consider adding the link of the website on the GitHub metadata about the repository. Thanks for the quick fix!
