### ISSUE TITLE
Request: Add a simpler heatmap cube example

### ISSUE THREAD

**Issue by briochemc** [lazarusA/BeautifulMakie#12]
Just a suggestion. After seeing [the cube example](https://lazarusa.github.io/BeautifulMakie/GeoPlots/temCubeESDL/)

<img width=66% src="https://lazarusa.github.io/BeautifulMakie/assets/scripts/output/temCubeESDL.png">

A [comment on SO](https://stackoverflow.com/questions/68646488/julia-how-to-plot-3d-heatmap?noredirect=1#comment121319286_68646488) asking for something similar in Plots.jl said "this code is complicated for me" (and that they wanted to use Plots.jl, but that's not my point here). 

Would it be possible to cook up a simpler cube example? The code is a little bit on the long side IMHO (Maybe building from the SO question code/data)

**Comment by lazarusA** [comment]
Yes, I do have something simpler. The thing is that this is for projecting heatmaps in 3d from climate data, lon, lat, time. So the pure assembly of faces is not that trivial. Here, in this mini package you can pass on your faces.  https://github.com/lazarusA/GeoCubesPlots.jl

**Comment by lazarusA** [comment]
I just saw the linked reference from above. And I think the approach used should be  `volume` and not heatmaps, as I said before the heatmaps are just 2d plots projected into 3d planes. A cube volume example is now here:  https://lazarusa.github.io/BeautifulMakie/surfWireLines/volume/
