### ISSUE TITLE
Link to Makie?

### ISSUE THREAD

**Issue by cormullion** [lazarusA/BeautifulMakie#13]
Spectacular page! :)  Awesome work.

I spent a few seconds looking for a copyable link to Makie.jl on the front page, to save me having to visit github.com - did I miss one? Perhaps a link at the bottom?

**Comment by lazarusA** [comment]
A link to the github repo or the docs?

**Comment by cormullion** [comment]
yes 😂

**Comment by lazarusA** [comment]
OK. I suppose both.

**Comment by lazarusA** [comment]
Done!, now if you hover Makie.jl in the main page your will be redirected to the Makie repo. And at the bottom a reference to the documentation has also been added.

**Comment by cormullion** [comment]
That's great!
