### ISSUE TITLE
Request: bring back the "gallery" of examples

### ISSUE THREAD

**Issue by jlchan** [lazarusA/BeautifulMakie#22]
One of the things I found really useful about the previous version of BeautifulMakie was that you could scroll through a gallery, look for a plot resembling what you wanted, and learn about the relevant functions used to create that plot. This was helpful especially since I didn't know the names of some types of plots I was looking for.

With the new version, if I don't know specifically what I'm looking for, I have to click through each link find a relevant example.

**Comment by lazarusA** [comment]
now is back. Well, at least some version of it.
