### ISSUE TITLE
Contour Complex function example missing 

### ISSUE THREAD

**Issue by AshtonSBradley** [lazarusA/BeautifulMakie#24]
https://lazarusa.github.io/BeautifulMakie/contour/ContourComplexF/

<img width="836" alt="Screen Shot 2022-05-27 at 4 29 55 PM" src="https://user-images.githubusercontent.com/24194258/170629271-ac577dc9-40ed-4482-8483-c142dbc84c5d.png">

**Comment by AshtonSBradley** [comment]
also, unrelated, but FYI in latest version, note that this https://github.com/JuliaPlots/Makie.jl/issues/1967 will make your legend in the LaTeX example look slightly broken

**Comment by lazarusA** [comment]
thanks, it's fixed now.https://github.com/lazarusA/BeautifulMakie/commit/f4428c588bfd3bc24a39d76ed6a744fff217082d
